udp:
  mcu_ip: 192.168.123.110
  port_to_mcu: 8881
  port_to_sdk: 8871

collision:
  # When a collision is detected, the robot arm will stop moving 
  # until the user executes `clearErrors()` in SDK
  open: false
  limitT: 10

# If cmdCache is true, z1_controller while execute ArmCmd.shift_command() 
# in unitree_arm_common.h when it doesn't receive a message from the SDK 
# in a single communication
cmdCache: false